name: FreeBSD Build Shared gcc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD GCC run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: intel/intel-ipsec-mb
      - name: Test FreeBSD GCC build
        id: tests
        uses: vmactions/freebsd-vm@v0.2.0
        with:
          usesh: true
          mem: 8192
          prepare: pkg install -y curl nasm gmake gcc
          run: |
            freebsd-version
            gmake CC=gcc -j 4
