name: Linux Build Static clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install -y nasm clang
    - uses: actions/checkout@v2
      with:
        repository: intel/intel-ipsec-mb
    - name: make static
      run: make CC=clang SHARED=n -j
